select * from course_statistics;
select * from courses;
select * from enrollments;
select * from lesson_progress;
select * from lessons;
select * from modules;
select * from notifications;
select * from roles;
select * from users;